language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
script:
  - python -m compileall ./oofster.py
  - python -m compileall ./ext
  - python -m compileall ./cogs
  - python ./oofster.py --test-run

notifications:
    email:
        on_success: never
        on_failure: always
