language: python
python:
  - "3.6"

install:
  - pip install -r bot/requirements.txt
script:
  - python -m compileall .bot//rickbot.py
  - python -m compileall ./bot/cogs
  - python ./bot/rickbot.py --test-run
