language: python
python:
  - "3.6"
  - "pypy-3.6"

install:
  - pip install -r requirements.txt
script:
  - python -m compileall ./rickbot.py
  - python -m compileall ./cogs
  - python ./rickbot.py --test-run
